# Generated by Django 4.2.17 on 2025-10-28 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="check_event_timestamp",
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="category",
            field=models.CharField(
                choices=[
                    ("irrigation", "Riego"),
                    ("fertilization", "Fertilización"),
                    ("phytosanitary", "Fitosanitarios"),
                    ("maintenance", "Labores de Cultivo"),
                    ("monitoring", "Monitoreo"),
                    ("harvest", "Cosecha"),
                    ("postharvest", "Poscosecha"),
                    ("analysis", "Análisis"),
                    ("pruning", "Poda"),
                    ("other", "Otro"),
                ],
                max_length=50,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "timestamp__lte",
                        datetime.datetime(
                            2025,
                            10,
                            28,
                            19,
                            34,
                            14,
                            603444,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                name="check_event_timestamp",
            ),
        ),
    ]
