# Generated by Django 4.2.17 on 2025-10-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_update_event_categories"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="check_event_timestamp",
        ),
    ]
