# Generated by Django 4.2.17 on 2025-11-12 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_timestamp_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "temperatura_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-20),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Temperatura Máxima (°C)",
                    ),
                ),
                (
                    "temperatura_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-20),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Temperatura Mínima (°C)",
                    ),
                ),
                (
                    "humedad_relativa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Humedad Relativa (%)",
                    ),
                ),
                (
                    "precipitacion_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precipitación (mm)",
                    ),
                ),
                (
                    "velocidad_viento_ms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Velocidad del Viento (m/s)",
                    ),
                ),
                (
                    "viento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sin viento", "Sin viento"),
                            ("Viento leve", "Viento leve"),
                            ("Viento moderado", "Viento moderado"),
                            ("Viento fuerte", "Viento fuerte"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Condición de Viento",
                    ),
                ),
                (
                    "radiacion_solar_wm2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Radiación Solar (W/m²)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Climático",
                "verbose_name_plural": "Eventos Climáticos",
                "db_table": "climate_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="FertilizationEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "producto",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "metodo_aplicacion",
                    models.CharField(
                        choices=[
                            ("Foliar", "Foliar"),
                            ("Fertirriego", "Fertirriego"),
                            ("Edáfica", "Edáfica"),
                            ("Inyección", "Inyección"),
                        ],
                        max_length=50,
                        verbose_name="Método de Aplicación",
                    ),
                ),
                (
                    "dosis",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Dosis",
                    ),
                ),
                (
                    "unidad_dosis",
                    models.CharField(
                        default="kg/ha", max_length=20, verbose_name="Unidad de Dosis"
                    ),
                ),
                (
                    "n_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Nitrógeno (%)",
                    ),
                ),
                (
                    "p_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Fósforo (%)",
                    ),
                ),
                (
                    "k_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Potasio (%)",
                    ),
                ),
                (
                    "volumen_caldo_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Volumen de Caldo (L)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Fertilización",
                "verbose_name_plural": "Eventos de Fertilización",
                "db_table": "fertilization_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="HarvestEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "variedad",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Variedad de Limón",
                    ),
                ),
                (
                    "volumen_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Volumen Total (kg)",
                    ),
                ),
                (
                    "rendimiento_kg_ha",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rendimiento (kg/ha)",
                    ),
                ),
                (
                    "calidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exportacion", "Exportación"),
                            ("primera", "Primera"),
                            ("segunda", "Segunda"),
                            ("tercera", "Tercera"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Calidad",
                    ),
                ),
                (
                    "numero_trabajadores",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Número de Trabajadores",
                    ),
                ),
                (
                    "horas_trabajo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas de Trabajo",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
            ],
            options={
                "verbose_name": "Evento de Cosecha",
                "verbose_name_plural": "Eventos de Cosecha",
                "db_table": "harvest_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="IrrigationEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("Aspersión", "Aspersión"),
                            ("Goteo", "Goteo"),
                            ("Surco", "Surco"),
                            ("Pivote", "Pivote"),
                            ("Manual", "Manual"),
                            ("Microaspersión", "Microaspersión"),
                        ],
                        max_length=50,
                        verbose_name="Método de Riego",
                    ),
                ),
                (
                    "duracion_minutos",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Duración (minutos)",
                    ),
                ),
                (
                    "fuente_agua",
                    models.CharField(
                        choices=[
                            ("Pozo", "Pozo"),
                            ("Río", "Río"),
                            ("Presa", "Presa"),
                            ("Red municipal", "Red municipal"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Fuente de Agua",
                    ),
                ),
                (
                    "volumen_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Volumen (m³)",
                    ),
                ),
                (
                    "presion_bar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Presión (bar)",
                    ),
                ),
                (
                    "ce_uScm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="CE (µS/cm)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                        verbose_name="pH",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Riego",
                "verbose_name_plural": "Eventos de Riego",
                "db_table": "irrigation_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="LaborCostEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "actividad",
                    models.CharField(
                        choices=[
                            ("Riego", "Riego"),
                            ("Fertilización", "Fertilización"),
                            ("Aplicación fitosanitaria", "Aplicación fitosanitaria"),
                            ("Poda", "Poda"),
                            ("Deshierbe", "Deshierbe"),
                            ("Cosecha", "Cosecha"),
                            ("Mantenimiento", "Mantenimiento"),
                            ("Transporte", "Transporte"),
                            ("Otra", "Otra"),
                        ],
                        max_length=100,
                        verbose_name="Actividad Realizada",
                    ),
                ),
                (
                    "numero_trabajadores",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Número de Trabajadores",
                    ),
                ),
                (
                    "horas_trabajo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas de Trabajo",
                    ),
                ),
                (
                    "costo_hora",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo por Hora",
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo Total",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Mano de Obra",
                "verbose_name_plural": "Eventos de Mano de Obra",
                "db_table": "labor_cost_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="MaintenanceEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "actividad",
                    models.CharField(
                        choices=[
                            ("Poda", "Poda"),
                            ("Deshierbe", "Deshierbe"),
                            ("Entutorado", "Entutorado"),
                            ("Aclareo de frutos", "Aclareo de frutos"),
                            ("Despunte", "Despunte"),
                            ("Cobertura vegetal", "Cobertura vegetal"),
                            ("Desbrote", "Desbrote"),
                            ("Raleo", "Raleo"),
                            ("Limpieza de canales", "Limpieza de canales"),
                            (
                                "Reparación de sistema de riego",
                                "Reparación de sistema de riego",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Actividad",
                    ),
                ),
                (
                    "horas_hombre",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Horas-Hombre",
                    ),
                ),
                (
                    "herramienta_equipo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Herramienta/Equipo Usado",
                    ),
                ),
                (
                    "numero_jornales",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Número de Jornales",
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objetivo de la Labor"
                    ),
                ),
                (
                    "porcentaje_completado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje Completado (%)",
                    ),
                ),
                (
                    "herramientas_desinfectadas",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="¿Herramientas Desinfectadas?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Labores",
                "verbose_name_plural": "Eventos de Labores",
                "db_table": "maintenance_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="MonitoringEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "plaga_enfermedad",
                    models.CharField(
                        max_length=200, verbose_name="Plaga/Enfermedad Observada"
                    ),
                ),
                (
                    "metodo_muestreo",
                    models.CharField(
                        choices=[
                            ("Visual directa", "Visual directa"),
                            ("Trampa adhesiva", "Trampa adhesiva"),
                            ("Trampa de luz", "Trampa de luz"),
                            ("Muestreo de suelo", "Muestreo de suelo"),
                            ("Muestreo foliar", "Muestreo foliar"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Método de Muestreo",
                    ),
                ),
                (
                    "incidencia",
                    models.CharField(
                        choices=[
                            ("Muy baja", "Muy baja"),
                            ("Baja", "Baja"),
                            ("Media", "Media"),
                            ("Alta", "Alta"),
                            ("Muy alta", "Muy alta"),
                        ],
                        max_length=20,
                        verbose_name="Incidencia",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Muy baja", "Muy baja"),
                            ("Baja", "Baja"),
                            ("Media", "Media"),
                            ("Alta", "Alta"),
                            ("Muy alta", "Muy alta"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "ubicacion_campo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Ubicación en el Campo",
                    ),
                ),
                (
                    "numero_muestras",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Número de Muestras",
                    ),
                ),
                (
                    "accion_recomendada",
                    models.TextField(
                        blank=True, null=True, verbose_name="Acción Recomendada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Monitoreo",
                "verbose_name_plural": "Eventos de Monitoreo",
                "db_table": "monitoring_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="OutbreakEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "tipo_problema",
                    models.CharField(
                        max_length=200, verbose_name="Tipo de Plaga/Enfermedad"
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("Baja", "Baja"),
                            ("Media", "Media"),
                            ("Alta", "Alta"),
                            ("Crítica", "Crítica"),
                        ],
                        max_length=20,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "metodo_deteccion",
                    models.CharField(
                        choices=[
                            ("Monitoreo rutinario", "Monitoreo rutinario"),
                            ("Inspección visual", "Inspección visual"),
                            ("Síntomas observados", "Síntomas observados"),
                            ("Reporte de trabajador", "Reporte de trabajador"),
                            ("Análisis de laboratorio", "Análisis de laboratorio"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Método de Detección",
                    ),
                ),
                (
                    "area_afectada_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Área Afectada (ha)",
                    ),
                ),
                (
                    "porcentaje_afectacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje de Afectación (%)",
                    ),
                ),
                (
                    "accion_inmediata",
                    models.TextField(
                        blank=True, null=True, verbose_name="Acción Inmediata Tomada"
                    ),
                ),
                (
                    "requiere_tratamiento",
                    models.BooleanField(
                        default=True, verbose_name="¿Requiere Tratamiento?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Brote",
                "verbose_name_plural": "Eventos de Brote",
                "db_table": "outbreak_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="PhytosanitaryEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "producto",
                    models.CharField(max_length=200, verbose_name="Nombre Comercial"),
                ),
                (
                    "ingrediente_activo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Ingrediente Activo",
                    ),
                ),
                (
                    "tipo_producto",
                    models.CharField(
                        choices=[
                            ("Insecticida", "Insecticida"),
                            ("Fungicida", "Fungicida"),
                            ("Herbicida", "Herbicida"),
                            ("Acaricida", "Acaricida"),
                            ("Nematicida", "Nematicida"),
                            ("Bactericida", "Bactericida"),
                            ("Coadyuvante", "Coadyuvante"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Producto",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        max_length=200, verbose_name="Plaga/Enfermedad/Maleza Objetivo"
                    ),
                ),
                (
                    "metodo_aplicacion",
                    models.CharField(
                        choices=[
                            ("Mochila manual", "Mochila manual"),
                            ("Mochila motorizada", "Mochila motorizada"),
                            ("Tractor", "Tractor"),
                            ("Dron", "Dron"),
                            ("Avión", "Avión"),
                            ("Fertirrigación", "Fertirrigación"),
                            ("Inyección al tronco", "Inyección al tronco"),
                        ],
                        max_length=50,
                        verbose_name="Método de Aplicación",
                    ),
                ),
                (
                    "dosis",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Dosis",
                    ),
                ),
                (
                    "unidad_dosis",
                    models.CharField(
                        default="L/ha", max_length=20, verbose_name="Unidad de Dosis"
                    ),
                ),
                (
                    "lote_producto",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Lote del Producto",
                    ),
                ),
                (
                    "volumen_caldo_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Volumen de Caldo (L)",
                    ),
                ),
                (
                    "presion_bar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Presión de Aplicación (bar)",
                    ),
                ),
                (
                    "intervalo_seguridad_dias",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Intervalo de Seguridad (días)",
                    ),
                ),
                (
                    "responsable_aplicacion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Responsable de la Aplicación",
                    ),
                ),
                (
                    "eficacia_observada",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("No evaluada", "No evaluada"),
                            ("Muy baja", "Muy baja"),
                            ("Baja", "Baja"),
                            ("Media", "Media"),
                            ("Alta", "Alta"),
                            ("Muy alta", "Muy alta"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Eficacia Observada",
                    ),
                ),
                (
                    "fitotoxicidad",
                    models.BooleanField(
                        default=False, verbose_name="¿Fitotoxicidad Observada?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Fitosanitario",
                "verbose_name_plural": "Eventos Fitosanitarios",
                "db_table": "phytosanitary_events",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="PostHarvestEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "producto",
                    models.CharField(
                        max_length=200, verbose_name="Producto Almacenado"
                    ),
                ),
                (
                    "cantidad_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cantidad (kg)",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "humedad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Humedad (%)",
                    ),
                ),
                (
                    "tipo_almacenamiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Almacenamiento",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
                (
                    "fecha_salida_prevista",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Salida Prevista"
                    ),
                ),
                (
                    "condiciones_observadas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Condiciones Observadas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Poscosecha",
                "verbose_name_plural": "Eventos Poscosecha",
                "db_table": "postharvest_events",
            },
            bases=("events.event",),
        ),
        migrations.RemoveField(
            model_name="event",
            name="payload",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="schema",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="version",
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="category",
            field=models.CharField(
                choices=[
                    ("irrigation", "Riego"),
                    ("fertilization", "Fertilización"),
                    ("phytosanitary", "Fitosanitarios"),
                    ("maintenance", "Labores de Cultivo"),
                    ("monitoring", "Monitoreo"),
                    ("harvest", "Cosecha"),
                    ("postharvest", "Poscosecha"),
                    ("other", "Otro"),
                ],
                max_length=50,
                verbose_name="Categoría",
            ),
        ),
    ]
