# Generated by Django 4.2.17 on 2025-10-27 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "season",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Temporada"
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Variedad"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaña",
                "verbose_name_plural": "Campañas",
                "db_table": "campaigns",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "surface_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Superficie (ha)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campo/Parcela",
                "verbose_name_plural": "Campos/Parcelas",
                "db_table": "fields",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("clima", "Clima"),
                            ("suelo", "Suelo"),
                            ("multivariable", "Multivariable"),
                        ],
                        default="multivariable",
                        max_length=50,
                        verbose_name="Tipo de Estación",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="Operacional"),
                ),
                (
                    "installed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Instalación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="catalogs.field",
                        verbose_name="Campo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estación de Monitoreo",
                "verbose_name_plural": "Estaciones de Monitoreo",
                "db_table": "stations",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["code"], name="fields_code_3d6ca0_idx"),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["is_active"], name="fields_is_acti_b79379_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["start_date", "end_date"], name="campaigns_start_d_5c7483_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["is_active"], name="campaigns_is_acti_6c57d0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="check_campaign_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["field"], name="stations_field_i_c1ea79_idx"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["is_operational"], name="stations_is_oper_74cde9_idx"
            ),
        ),
    ]
